Tracker:AddLocations("locations/Aqours Memoria.json")
Tracker:AddLocations("locations/Coral Hill.json")
Tracker:AddLocations("locations/Crystalline Grotto.json")
Tracker:AddLocations("locations/Grotto.json")
Tracker:AddLocations("locations/Infernal Altar.json")
Tracker:AddLocations("locations/Ruins.json")
Tracker:AddLocations("locations/Sea of Trees.json")
Tracker:AddLocations("locations/Shipwreck.json")
Tracker:AddLocations("locations/Sunken Temple.json")
Tracker:AddLocations("locations/Sunken Volcano.json")
Tracker:AddLocations("locations/Mysterious Dungeon.json")
